### ISSUE TITLE
Just got an error on compose up

### ISSUE THREAD

**Issue by RickCd** [cjmatta/ConfluentPlatformWikipediaDemo#1]
Hey Chris,  just pulled down the demo and get an error on compose up, 
Pulling repository docker.io/cmatta/wikipediademoconnect
ERROR: Tag latest not found in repository docker.io/cmatta/wikipediademoconnect

Could it be a typo in the .yml file ?   I didn't see a repo with that name.....

**Comment by cjmatta** [comment]
About to take off, let me check it when I land.

**Comment by cjmatta** [comment]
close this was resolved
